### ISSUE TITLE
ss2json doesn't properly bundle

### ISSUE THREAD

**Issue by rgdonohue** [abetomo/node-ss2json#48]
Great package! Thank you.

I'm having issues trying to bundle using either webpack, broswerify, or rollup (see error from browserify below). Is it not intended to be used outside of a server environment?

![image](https://user-images.githubusercontent.com/1952205/29724918-a27e531e-8987-11e7-9187-0779f5f8510c.png)

**Comment by abetomo** [comment]
@rgdonohue Thanks for the report.

We only considered operation in the server environment.
Please wait just a moment as I will try to fix it.
I will reply within a week.

**Comment by abetomo** [comment]
@rgdonohue I released the modified one. It is 1.1.0.
I would be pleased if you could try it.

**Comment by rgdonohue** [comment]
@abetomo Looks like I'm running into this issue now: [https://github.com/google/google-api-nodejs-client/issues/572](https://github.com/google/google-api-nodejs-client/issues/572).

May be best to simply use a Node API to pull the data from Google spreadsheet on the server and then send the parsed data to the client?

**Comment by abetomo** [comment]
@rgdonohue I agree. That might be better.

Implement any functions you need. Please feel free to open the issue.

**Comment by abetomo** [comment]
Please feel free to open if there is something again.
